### ISSUE TITLE
Bring this project into salt's codebase

### ISSUE THREAD

**Issue by twangboy** [mosen/salt-osx#1]
I'm one of the developers at SaltStack. I've been working on giving OSX some more love and I came across this repo. I really like what you've done here. How would you feel about bringing this in to the main salt repo? 

We would need to modify the names a little to mesh with how we're handling multiple OS's.

What do you think?

**Comment by mosen** [comment]
Hey there,
Bringing some OSX support to salt would be great, however my repo has quite a few modules ranging from completely broken to fairly well tested.

I dont have a problem changing names to accommodate cross platform support.

I noticed that the comment references user.present, and OSX support for user passwords is incredibly hacky at the moment. There are a couple of different approaches depending on whether you are strict about reducing dependencies or not.

**Comment by weswhet** [comment]
some of these have been moved into core already. we'll work on moving more of them in.
